Repository RackReaver/FinPack, pull requests merged in 2021-12, with the labels that each got.

#6 Hotfix #5
  .github/workflows/main.yml
Labels: bug

#10 Fix grammer issue.
  README.md
Labels: bug

#12 Add/update file headers.
  finpack/core.py
  finpack/reports/balsheet.py
  finpack/utils.py
  setup.py
  tests/test_core.py
Labels: documentation

#15 feature: init function [#7]
  finpack/core.py
Labels: enhancement

#16 Bug/14 level arg should be kwarg
  finpack/core.py
Labels: bug

#17 Refactor/seperate core functions
  finpack/core.py
  finpack/core/__init__.py
  finpack/core/exceptions.py
  finpack/core/init.py
  finpack/core/loader.py
  finpack/core/models.py
  finpack/reports/allocation.py
  finpack/reports/balsheet.py
  finpack/reports/cashflow.py
  tests/test_core.py
Labels: enhancement

#19 Add how to use data for finpack cli.
  README.md
Labels: documentation

#22 Error capturing version for cli [#20]
  finpack/VERSION
  finpack/core/cli.py
  pyproject.toml
Labels: bug

#24 BugFix: #23 Removed known issue.
  finpack/core/cli.py
Labels: bug

#28 doc: Simplified project description.
  README.md
  logo.png
  pyproject.toml
  setup.py
Labels: documentation

#29 Bug Fix: Add sort post append.
  finpack/core/models.py
Labels: bug

#30 feat: Add custom date option balsheet
  finpack/core/cli.py
  finpack/core/models.py
  finpack/reports/balsheet.py
  tests/test_core.py
Labels: enhancement

#31 docs: 📝 Fix multiple issues
  README.md
  finpack/core/cli.py
Labels: documentation

#33 test: ✅ Renamed setup and teardown and switched to class func's
  tests/test_core.py
Labels: bug

#34 fix: :bug: Escape backslash in core.cli.__doc__
  finpack/core/cli.py
Labels: bug

#35 test: ✅ Add tests for core.cli.__doc__
  tests/test_cli.py
Labels: enhancement

#36 docs 📝 Add LICENSE.md
  LICENSE
Labels: documentation

#37 docs 📝 Create CONTRIBUTE.md
  CONTRIBUTE.md
Labels: documentation, enhancement

#38 ci: 💚 Add caching to github workflow
  .github/workflows/main.yml
Labels: enhancement

#39 build: 👷 Populate pyproject.toml
  pyproject.toml
Labels: enhancement

#43 docs: 📝 Add demo to README.md
  README.md
  demo.gif
Labels: documentation, enhancement

#44 build: 👷 Remove setup.py
  setup.py
Labels: documentation

#45 docs: 📝 Fixed broken link in README.md
  README.md
Labels: documentation

#48 fix: 🐛 Intended code properly
  finpack/reports/balsheet.py
Labels: bug

#51 refactor: :recycle: Improve readability, remove bloat and added basic verbose logging.
  finpack/core/loader.py
  tests/test_core.py
Labels: refactor

#52 fix: :bug: Add missing if statement
  finpack/core/loader.py
Labels: bug

#55 feat: :sparkles: Add verbose option to terminal app
  finpack/core/cli.py
Labels: enhancement

#57 refactor: :recycle: Remove underscore from add_char utility function
  finpack/reports/balsheet.py
  finpack/utils.py
Labels: refactor

#58 refactor: :recycle: Switch Account.value return value from str to float
  finpack/core/models.py
Labels: refactor

#59 Bugfix/fix test account value function
  tests/test_core.py
Labels: bug
